apiVersion: v1
kind: Service
metadata:
    name: weaversenpaipipelinesdotnetcoredocker
spec:
    type: LoadBalancer
    ports:
    - port: 8000 
    selector:
        app: weaversenpaipipelinesdotnetcoredocker